// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujzWuUNFAmwEVkYLAoXYeUWdOpe0w9ZM',
    appId: '1:437241531792:web:7f641b1ae5b556a6647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    authDomain: 'chatting-app-528d7.firebaseapp.com',
    storageBucket: 'chatting-app-528d7.appspot.com',
    measurementId: 'G-FL02Q4ZQKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz7juXS1WLlVWgp6tZKuEkobSGUnd5F6k',
    appId: '1:437241531792:android:5105e2a4c2f83026647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    storageBucket: 'chatting-app-528d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIu-6NDAq2ycKDum3B1KTMJ4C2keuIPx4',
    appId: '1:437241531792:ios:9701248bebc13be1647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    storageBucket: 'chatting-app-528d7.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIu-6NDAq2ycKDum3B1KTMJ4C2keuIPx4',
    appId: '1:437241531792:ios:9701248bebc13be1647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    storageBucket: 'chatting-app-528d7.appspot.com',
    iosBundleId: 'com.example.chattingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDujzWuUNFAmwEVkYLAoXYeUWdOpe0w9ZM',
    appId: '1:437241531792:web:6c549312408b0f07647715',
    messagingSenderId: '437241531792',
    projectId: 'chatting-app-528d7',
    authDomain: 'chatting-app-528d7.firebaseapp.com',
    storageBucket: 'chatting-app-528d7.appspot.com',
    measurementId: 'G-QZ38JVFC0B',
  );
}
